name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: '&#x1f507; Congrats your first issue resolved 00_&#x1f507__01'
        pr-message: '&#128263 congrats your first PR - :mute:'
